### ISSUE TITLE
[Bug] Follower levels not visible

### ISSUE THREAD

**Issue by penguinsane** [failcoder/Supervillain_UI#72]
Most recent update killed being able to see follower levels.

http://puu.sh/dHEc3/230b0e5757.jpg

**Comment by failcoder** [comment]
I can not reproduce this issue. latest version shows the levels as expected.

**Comment by failcoder** [comment]
MasterPlan support may not be possible, I am still looking into it.

**Comment by SourSkittles** [comment]
I found out what the issue is, it's not an issue with master plan at all. the problem is with Garrison Mission Manager as it's the addon that does the follower lvls/ilvls like how penguinsane has in the pictures. I disabled that addon and just left master plan on and the lvls and ilvls show up just fine but turning on Garrison Mission Manager and the levels and ilvls disappear again. 

Addon link is http://www.curse.com/addons/wow/garrison-mission-manager
